name: ecommerce_analytics
version: 1.0.0
config-version: 2
profile: ecommerce_analytics

model-paths: ["models"]
target-path: target
clean-targets:
  - target
  - dbt_packages

vars:
  silver_glob: "../data/processed/silver/ecommerce_transactions/**/*.parquet"

models:
  ecommerce_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
